### ISSUE TITLE
1.3 breaking change

### ISSUE THREAD

**Issue by JeroenDeDauw** [scssphp/scssphp#245]
Just like [with 1.2](https://github.com/scssphp/scssphp/issues/170), it seems like 1.3 is breaking things again.

See https://github.com/ProfessionalWiki/chameleon/issues/201

**Comment by stof** [comment]
Can you share a reproducing case ?

**Comment by Cerdic** [comment]
Error is
```
SCSS compile error: ` ul li a .tocnumber` is not a valid Selector in ` ul li a .tocnumber`: failed at ` ul li a .tocnumber` ScssPhp\ScssPhp\Compiler::evalSelectors on line 1, at column 0
```

and the guilty code is
```
$selector: "";
@for $i from 1 through 6 {
	$selector: "#{$selector} ul li";
	#{$selector} a .tocnumber { min-width: $cmln-toc-entry-number-padding-right + 0.25rem + 0.75rem * $i; }
}
```

I can see a space at the start of the selector, and I think indeed this is the reason of this failure (This should work of course)

The reason is we added in this release a compilation-time parsing of selectors that are the result of evaluation to check they are valid, and here the space at the start make this validation fail

**Comment by Cerdic** [comment]
This can be reproduced with single test case:
```
$selector: " ul li";
#{$selector} a .tocnumber {
	min-width: 100%;
}
```

**Comment by stof** [comment]
According to https://www.sassmeister.com/gist/c5ba452d2056365634d6b216f3fe7876 this should be valid Sass though.
The selector validation probably does not implement things properly when using interpolation.

Note: see https://gist.github.com/stof/c5ba452d2056365634d6b216f3fe7876 for the source of that link, as sassmeister seems to have a bug which I reported at https://github.com/jedfoster/SassMeister/issues/216

**Comment by Cerdic** [comment]
ok @stof I have a fix but a bigger issue : the master is broken when I lauch the tests see #246 
(and sorry no time to fix it now)

**Comment by stof** [comment]
I'll look into it. Probably a conflict between 2 merged PRs which were green on their own.

**Comment by bertrandgorge** [comment]
Hello all, thanks for you help! Really cool!

**Comment by Cerdic** [comment]
The bug is fixed in the master branch. 

@stof shall we now make a 1.3 branch starting from the 1.3 tag to be able to safely relase a 1.3.1 with fix, without worrying about the refactoring that already started on the master? 
I have the feeling this is a safe solution.
Or do you feel comfortable enough to release a 1.4 version based on the master branch? I fear a bit this could become a running gag, with shipping new small bug(s) in what is supposed to be a fix-release.

Any opinion about that @robocoder?

**Comment by stof** [comment]
I would go for 1.4. The big (risky) refactoring is not merged yet (as it targets 2.0). To me, we could release a new 1.x release based on it.

@JeroenDeDauw can you try the latest master branch ?

**Comment by bertrandgorge** [comment]
Hello, I just tested with master and it works well !

**Comment by stof** [comment]
@bertrandgorge 1.4.0 is now released and includes the fix.

**Comment by bertrandgorge** [comment]
Thanks a lot Christophe!  I confirm that the bug is gone with this new release!
